import type { AwardWin } from "@/lib/anime-awards";

export const CR_CATEGORY_SHORT: Record<string, string> = {
  anime_of_the_year: "Winner",
  best_continuing_series: "Continuing",
  best_new_series: "New",
  best_film: "Film",
  best_original_anime: "Original",
  best_animation: "Animation",
  best_director: "Director",
  best_action: "Action",
  best_fantasy: "Fantasy",
  best_isekai: "Isekai",
  best_drama: "Drama",
  best_comedy: "Comedy",
  best_romance: "Romance",
  best_slice_of_life: "Slice",
  best_mystery: "Mystery",
  best_horror: "Horror",
  best_sports: "Sports",
  best_supernatural: "Supernatural",
  best_scifi: "Sci-Fi",
  best_background_art: "BG Art",
  best_character_design: "Char Design",
  best_cinematography: "Cinematography",
  best_art_direction: "Art Direction",
  best_score: "Score",
  best_song: "Song",
  best_opening: "Opening",
  best_ending: "Ending",
  best_boy: "Boy",
  best_girl: "Girl",
  best_protagonist: "Hero",
  best_antagonist: "Villain",
  best_main_character: "Main Char",
  best_supporting: "Supporting",
  best_couple: "Couple",
  best_fight: "Fight",
  best_bromance: "Bromance",
  best_girls_love: "GL",
  best_boys_love: "BL",
  must_protect: "Must Protect",
  global_impact: "Global Impact",
  best_cgi: "CGI",
  heartwarming_scene: "Heartwarming",
  best_tv: "TV",
  best_ova: "OVA",
  best_packaged: "Packaged",
  best_network: "Network",
  best_theme_song: "Song",
  grand_prize: "Grand Prize",
  excellence: "Excellence",
  new_face: "New Face",
  social_impact: "Social",
  best_short: "Short",
  best_va: "VA",
  best_character: "Character",
  best_adventure: "Adventure",
  best_suspense: "Suspense",
  best_psychological: "Psychological",
};

export function shortCategory(win: AwardWin): string {
  const fromMap = CR_CATEGORY_SHORT[win.categoryKey];
  if (fromMap) return fromMap;
  return win.categoryName.replace(/^Best\s+/i, "").replace(/Award$/i, "").trim();
}
