import type { SectionId } from "./shared";

export const SECTION_ICONS: Record<SectionId, string> = {
  basics: "Rocket",
  account: "UserRound",
  library: "Library",
  trakt: "CircleUser",
  anilist: "ListVideo",
  mal: "BookMarked",
  simkl: "RefreshCw",
  letterboxd: "Clapperboard",
  relay: "Radio",
  streaming: "Waypoints",
  streamFilters: "Filter",
  p2p: "Share2",
  plugins: "Puzzle",
  language: "Languages",
  subtitles: "Captions",
  player: "Play",
  mpv: "Gauge",
  anime: "Sparkles",
  shaders: "Wand2",
  playerLayout: "LayoutDashboard",
  hotkeys: "Keyboard",
  controllers: "Gamepad2",
  theme: "Palette",
  badges: "BadgeCheck",
  awardIcons: "Trophy",
  webhooks: "Webhook",
  bug: "Bug",
  support: "Heart",
  licenses: "Scale",
  icons: "Shapes",
  remotes: "SmartphoneNfc",
  tv: "Tv",
  bigPicture: "MonitorPlay",
  storage: "HardDrive",
  trackers: "Activity",
  updates: "ArrowUpCircle",
  advanced: "SlidersHorizontal",
};
