export type TvChoice = { value: string; label: string };

export const TV_UI_LANGUAGES: TvChoice[] = [
  { value: "en", label: "English" },
  { value: "ar", label: "Arabic" },
  { value: "pt", label: "Portuguese" },
  { value: "ru", label: "Russian" },
];

export const TV_LANGS: TvChoice[] = [
  { value: "en", label: "English" },
  { value: "es", label: "Spanish" },
  { value: "es-419", label: "Spanish (Latin America)" },
  { value: "fr", label: "French" },
  { value: "de", label: "German" },
  { value: "it", label: "Italian" },
  { value: "ja", label: "Japanese" },
  { value: "ko", label: "Korean" },
  { value: "zh", label: "Chinese" },
  { value: "ru", label: "Russian" },
  { value: "pt", label: "Portuguese" },
  { value: "pt-BR", label: "Portuguese (Brazil)" },
  { value: "ar", label: "Arabic" },
  { value: "hi", label: "Hindi" },
  { value: "th", label: "Thai" },
  { value: "vi", label: "Vietnamese" },
  { value: "tr", label: "Turkish" },
  { value: "pl", label: "Polish" },
  { value: "nl", label: "Dutch" },
  { value: "sv", label: "Swedish" },
  { value: "no", label: "Norwegian" },
  { value: "da", label: "Danish" },
  { value: "fi", label: "Finnish" },
  { value: "he", label: "Hebrew" },
];

export const TV_SERVICES: TvChoice[] = [
  { value: "netflix", label: "Netflix" },
  { value: "disney", label: "Disney+" },
  { value: "hulu", label: "Hulu" },
  { value: "prime", label: "Prime Video" },
  { value: "apple", label: "Apple TV+" },
  { value: "max", label: "Max" },
  { value: "paramount", label: "Paramount+" },
  { value: "peacock", label: "Peacock" },
  { value: "crunchyroll", label: "Crunchyroll" },
  { value: "amcplus", label: "AMC+" },
  { value: "starz", label: "STARZ" },
  { value: "shudder", label: "Shudder" },
  { value: "tubi", label: "Tubi" },
  { value: "plutotv", label: "Pluto TV" },
  { value: "roku", label: "The Roku Channel" },
  { value: "fubo", label: "Fubo" },
  { value: "mgmplus", label: "MGM+" },
  { value: "philo", label: "Philo" },
  { value: "britbox", label: "BritBox" },
  { value: "acorntv", label: "Acorn TV" },
  { value: "mubi", label: "MUBI" },
  { value: "curiositystream", label: "CuriosityStream" },
  { value: "kanopy", label: "Kanopy" },
  { value: "hoopla", label: "Hoopla" },
  { value: "pbs", label: "PBS" },
  { value: "cw", label: "The CW" },
  { value: "hidive", label: "HIDIVE" },
];

export const TV_SERVICES_DEFAULT: string[] = [
  "netflix",
  "disney",
  "hulu",
  "prime",
  "apple",
  "max",
  "paramount",
  "peacock",
  "crunchyroll",
  "amcplus",
  "starz",
  "shudder",
];

export const TV_BUILTIN_THEME_IDS: string[] = [
  "cool-grey",
  "nord",
  "stremio",
  "crunch",
  "tokyo-night",
  "dracula",
  "forest",
  "noir",
  "aurora",
  "minui",
  "elegantfin",
  "velvet",
  "feishin",
];
